# SPDX-License-Identifier: Apache-2.0

"""Public contracts for immutable Memory Service evidence, history, and releases."""

from areal.v2.memory_service.errors import (
    CandidateConflictError,
    CandidateNotFoundError,
    EvidenceConflictError,
    EvidenceNotFoundError,
    MemoryBoundaryMismatchError,
    MemoryConsumerAckConflictError,
    MemoryConsumerAckNotFoundError,
    MemoryDeliveryConflictError,
    MemoryDeliveryNotFoundError,
    MemoryExposureConflictError,
    MemoryExposureNotFoundError,
    MemoryQueryConflictError,
    MemoryQueryNotFoundError,
    MemoryServiceError,
    ReleaseConflictError,
    ReleaseNotFoundError,
    RevisionConflictError,
    RevisionNotFoundError,
)
from areal.v2.memory_service.history_store import (
    InMemoryMemoryHistoryStore,
    MemoryHistoryStore,
)
from areal.v2.memory_service.history_types import (
    CandidateProposal,
    MemoryCandidate,
    MemoryRevision,
    RevisionOperation,
    RevisionProposal,
)
from areal.v2.memory_service.release_store import (
    InMemoryMemoryReleaseStore,
    MemoryReleaseStore,
)
from areal.v2.memory_service.release_types import MemoryRelease, ReleaseManifest
from areal.v2.memory_service.runtime_store import (
    InMemoryMemoryRuntimeStore,
    MemoryConsumerCallV1,
    MemoryRenderOutputV1,
    MemoryRetrievalOutputV1,
    MemoryRuntimeConsumer,
    MemoryRuntimeRenderer,
    MemoryRuntimeRetriever,
    MemoryRuntimeStore,
)
from areal.v2.memory_service.runtime_types import (
    MemoryConsumerAckV1,
    MemoryConsumerKind,
    MemoryDeliveryV1,
    MemoryEvidenceRefV1,
    MemoryExposureStatus,
    MemoryExposureV1,
    MemoryQueryAttemptV1,
    MemoryQueryItemV1,
    MemoryQueryResultV1,
    MemoryQuerySpecV1,
    MemoryRenderedRevisionRangeV1,
    MemoryRenderedRevisionSpanV1,
    MemoryRevisionRefV1,
)
from areal.v2.memory_service.store import EvidenceStore, InMemoryEvidenceStore
from areal.v2.memory_service.types import (
    EvidenceEvent,
    EvidenceKind,
    EvidenceRecord,
    MemoryScope,
)

__all__ = [
    "CandidateConflictError",
    "CandidateNotFoundError",
    "CandidateProposal",
    "EvidenceConflictError",
    "EvidenceEvent",
    "EvidenceKind",
    "EvidenceNotFoundError",
    "EvidenceRecord",
    "EvidenceStore",
    "InMemoryEvidenceStore",
    "InMemoryMemoryHistoryStore",
    "InMemoryMemoryReleaseStore",
    "InMemoryMemoryRuntimeStore",
    "MemoryBoundaryMismatchError",
    "MemoryCandidate",
    "MemoryConsumerAckConflictError",
    "MemoryConsumerAckNotFoundError",
    "MemoryConsumerAckV1",
    "MemoryConsumerCallV1",
    "MemoryConsumerKind",
    "MemoryDeliveryConflictError",
    "MemoryDeliveryNotFoundError",
    "MemoryDeliveryV1",
    "MemoryEvidenceRefV1",
    "MemoryExposureConflictError",
    "MemoryExposureNotFoundError",
    "MemoryExposureStatus",
    "MemoryExposureV1",
    "MemoryHistoryStore",
    "MemoryQueryAttemptV1",
    "MemoryQueryConflictError",
    "MemoryQueryItemV1",
    "MemoryQueryNotFoundError",
    "MemoryQueryResultV1",
    "MemoryQuerySpecV1",
    "MemoryRelease",
    "MemoryReleaseStore",
    "MemoryRevision",
    "MemoryRevisionRefV1",
    "MemoryRenderedRevisionRangeV1",
    "MemoryRenderedRevisionSpanV1",
    "MemoryRetrievalOutputV1",
    "MemoryRenderOutputV1",
    "MemoryRuntimeConsumer",
    "MemoryRuntimeRenderer",
    "MemoryRuntimeRetriever",
    "MemoryRuntimeStore",
    "MemoryScope",
    "MemoryServiceError",
    "ReleaseConflictError",
    "ReleaseManifest",
    "ReleaseNotFoundError",
    "RevisionConflictError",
    "RevisionNotFoundError",
    "RevisionOperation",
    "RevisionProposal",
]
